### ISSUE TITLE
Check for similar string?

### ISSUE THREAD

**Issue by smironescu** [marionebl/jsonlint-cli#4]
Hello,

I'm a bit new into this, but nice project. Well done.
I have a question. Can it be configured to search for a duplicated string?
For instance:

`{
"name": "abs",
"name: "abc"
}`

Error: string "name" is duplicated.

**Comment by marionebl** [comment]
`jsonlint-cli` uses https://github.com/zaach/jsonlint for linting and does nothing to extend the linting capabilities, rather adds json schema validation on top – I'd keep jsonlint-cli this way to keep it small and maintainable.

This means you could throw in your two cents here: https://github.com/zaach/jsonlint/issues/13 

I would not bet on jsonlint adding duplicate key checking anytime soon though, as it actually conforms to standards: http://stackoverflow.com/a/21833017/3263412
